language: perl

# system perl
#perl:

before_install:
    - perlbrew switch-off
    - sudo apt-get update
    - sudo apt-get clean
    - sudo apt-get install lynx wget curl

    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get -q -y install mysql-server
    - mysqladmin -u root password nerfnerf
    - export DEBIAN_FRONTEND=''

install:
    - echo 'deb http://debian.koha-community.org/koha squeeze main' | sudo tee /etc/apt/sources.list.d/koha.list

    - sudo wget -O - http://debian.koha-community.org/koha/gpg.asc | sudo apt-key add -

    - sudo apt-get update
    - sudo apt-get install koha-common > /dev/null

    - echo 'NameVirtualHost *:80'   | sudo tee /etc/apache2/ports.conf
    - echo 'Listen 80'              | sudo tee -a /etc/apache2/ports.conf
    - echo 'Listen 8080'            | sudo tee -a /etc/apache2/ports.conf

#    - sudo cp -v debian/templates/koha-sites.conf /etc/koha

    - cat /etc/apache2/ports.conf


#    - cd /etc/koha
#    - sudo curl -O  https://raw.github.com/KohaAloha/Koha-Dev/trav-packages/debian/templates/koha-sites.conf
    - wget -O /etc/koha/koha-sites.conf https://raw.github.com/KohaAloha/Koha-Dev/trav-packages/debian/templates/koha-sites.conf



    - cat /etc/koha/koha-sites.conf


    - sudo a2dissite 000-default
    - sudo a2enmod rewrite
    - sudo a2enmod deflate
    - sudo apache2ctl restart

    - sudo koha-create --create-db lib1
    - sudo a2ensite lib1


    - wget  http://127.0.1.1:80 -O /tmp/opac.html
    - wget  http://127.0.1.1:8080 -O /tmp/staff.html
    - cat /tmp/opac.html
    - cat /tmp/staff.html

script:
    - echo 0
